### PR TITLE
Secure vs Insecure Build Diffs

### PR DESCRIPTION
**Pull request by chrisdennis**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
What I'm seeing is that the only diffs were in the `pom.properties` and the `MANIFEST.MF` files. There were no diffs anywhere else in any of the `.class` files, is this accurate?

**Comment by chrisdennis** [comment]
There is one jar file that contains some class file diffs due to javac's inner class numbering changes: https://github.com/ehcache/ehcache3-release-validation/pull/1/files#diff-c13b8aef805e19531821b11ff6f019c2

**Comment by JLLeitschuh** [comment]
Thanks for pointing that one out explicitly.
Given these results, I concur that there is no evidence of compromise.

**Review by JLLeitschuh — APPROVED** [review]
Awesome work, this PR LGTM!

**Review by anthonydahanne — APPROVED** [review]

**Review by jhouserizer — APPROVED** [review]

**Pull request merged**
